"""add vendor unique constraint

Revision ID: 96d154c3ff9c
Revises: cc56096d7df6
Create Date: 2026-06-26 06:03:21.374515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d154c3ff9c'
down_revision: Union[str, Sequence[str], None] = 'cc56096d7df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_vendors_owner_id'), table_name='vendors')
    op.create_index(op.f('ix_vendors_owner_id'), 'vendors', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_owner_id'), table_name='vendors')
    op.create_index(op.f('ix_vendors_owner_id'), 'vendors', ['owner_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    # ### end Alembic commands ###
