"""add indexes + user.role

Revision ID: cc56096d7df6
Revises: 99a2263a451a
Create Date: 2026-06-24 14:42:17.876029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc56096d7df6'
down_revision: Union[str, Sequence[str], None] = '99a2263a451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_payment_reference'), 'orders', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_products_created_at', 'products', ['created_at'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_constraint(op.f('vendors_owner_id_key'), 'vendors', type_='unique')
    op.create_index(op.f('ix_vendors_created_at'), 'vendors', ['created_at'], unique=False)
    op.create_index('ix_vendors_owner_id', 'vendors', ['owner_id'], unique=False)
    op.create_index('ix_vendors_verified', 'vendors', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vendors_verified', table_name='vendors')
    op.drop_index('ix_vendors_owner_id', table_name='vendors')
    op.drop_index(op.f('ix_vendors_created_at'), table_name='vendors')
    op.create_unique_constraint(op.f('vendors_owner_id_key'), 'vendors', ['owner_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_index('ix_products_created_at', table_name='products')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_reference'), table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    # ### end Alembic commands ###
